### ISSUE TITLE
[Discussion] Submodules or one monolithic repo?

### ISSUE THREAD

**Issue by fieldOfView** [z25/ZOCPApps#1]
How shall we use this repository? As one big repo with many apps in different stages of development, or a collection of submodules?

I can add https://github.com/fieldofview/pyZOSC as a submodule (named zosc).

**Comment by fieldOfView** [comment]
Why not both?
http://cdn.meme.am/instances/500x/55226207.jpg

**Comment by sphaero** [comment]
i'm ok with going for submodules for now. We just need to make sure we add an explicit instruction for it as submodules don't drop out if the sky with git.
